language: android
jdk: oraclejdk7
sudo: false

branches:
   only:
      - unstable

android:
   components:
      - build-tools-23.0.1
      - android-23
      - sys-img-armeabi-v7a-android-23
      - android-22
      - sys-img-armeabi-v7a-android-22
      - extra-google-m2repository
      - extra-android-m2repository

env:
   global:
      # install timeout in minutes
      - ADB_INSTALL_TIMEOUT=8
   matrix:
      # there is no difference between version 19 and 20 for phone and tablet platforms
      # add new value here if need to support new API version
      - ANDROID_TARGET=android-19
      - ANDROID_TARGET=android-21
      - ANDROID_TARGET=android-22
      # block the run on this version for travis ci issue untill it is fixed
      # - ANDROID_TARGET=android-23

licenses:
    - android-sdk-license-5be876d5

# Create and start the emulator
before_script:
   - echo no | android create avd --force -n test -t $ANDROID_TARGET  --abi armeabi-v7a -c 128M
   - emulator -avd test -no-skin -no-audio -no-window &
   - android-wait-for-emulator
   - adb shell input keyevent 82
   - adb shell input keyevent 84

#Build all projects and run the tests
script:
   - travis_wait 30 ./gradlew :libs:SalesforceSDK:connectedAndroidTest
   - travis_wait 30 ./gradlew :libs:SmartStore:connectedAndroidTest
   - travis_wait 30 ./gradlew :libs:SmartSync:connectedAndroidTest
   # disable the test to reduce the impact for other tests, just build it
   # will add it back once fix the test issue
   - ./gradlew :libs:SalesforceHybrid:assembleDebug
   - ./gradlew :libs:SalesforceReact:assembleDebug
   - travis_wait 30 ./gradlew :native:NativeSampleApps:RestExplorer:connectedAndroidTest
   - travis_wait 30 ./gradlew :native:TemplateApp:connectedAndroidTest
