system("npm install shelljs@0.7.0")
system("./install.sh")

lane :PR do
    begin
    gradle(
 task:":libs:SalesforceAnalytics:connectedAndroidTest :libs:SmartStore:connectedAndroidTest :libs:SmartSync:connectedAndroidTest :libs:SalesforceHybrid:connectedAndroidTest",
        flavor: "WorldDomination",
        build_type: "Debug"
        flags: "--continue --no-daemon --profile --stacktrace"
    )
end
